bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: DUegrlaIU0SyOcx2eJ2g0zl0Yc66kkP6xtjQlFVjG8mxaEdSe2y9UT7A1xJSm/TivDeJJi/O5+rwHWqaqSx1WwjLcZ0XWB8ygxMok4f07u4I6bXziSuUh9Z3jsv2NVpsw2kCE9FLpybFfOWS/5UWMdJSmFAMEWl+ngDaYhQPEbLX0hZHAkx9PUJvo+/zh4iwVgvD/Nbn7LpR66VJhr3Lv1nR4/NXM2/FOx9FTAjjDx96Y+1o0A7qJZeA1p2xhOxYEnQtQ9LL4RVvMDE+drlsygf6UvfTLOFwJYaV4N89GIfDRKp9nBiotiOvFJxxEDtpbQRoFZB4znuHu4+vtsLEZ16zTJp1KRf9edV0ZJ3pAQ5GXIf0GXzYeoLHDHjIMaDFs4b9vp6v4LG3hvzd3XQt6WYyf7P1s3Ycj23uBt7+F0sBXamF7KgMRXYn7XXgpGGGTEs3bbWbAbXxYBqqKUmG0mudRWbi2gToKMA6Z7BY5NknAdzdUqBaNLPeyXN3Wuf+O429wMdQk8SIOxftqeWhnF5SHg2FNhi/rdO6C5xQLbJDz/+3nRiALck4NB9giKmWPoiLqgy0fh2dM2SRede9PHHJKrWWSHyfhqcVTuuLDFq4BqGxn+tTouhQAT06XSZxyx4sWJ2DUJbPHY9xrMoLIH1kSZILrUpKdcOi3MgBeiI=
conda_forge_output_validation: true
